name: ci
on:
  pull_request:
  merge_group:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: show
        run: |
          echo "event=${{ github.event_name }} sha=${{ github.sha }} ref=${{ github.ref }}"
          sleep 20
